import type { ReactNode } from "react"
import { DocsLayout } from "fumadocs-ui/layouts/docs"

import { WorkspaceUILogo } from "@/components/workspaceui-logo"
import { source } from "@/lib/source"

// Sidebar tree is generated by fumadocs from the docs content + meta.json
// (ordering/titles live in src/content/docs/**/meta.json).
const links = [{ text: "Blocks", url: "/blocks", active: "nested-url" as const }]

export default function Layout({ children }: { children: ReactNode }) {
  return (
    <DocsLayout
      tree={source.pageTree}
      links={links}
      githubUrl="https://github.com/jayclydeTags/workspaceui"
      nav={{ title: <WorkspaceUILogo className="h-5 w-auto" /> }}
    >
      {children}
    </DocsLayout>
  )
}
